apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
  template:
    metadata:
      labels:
        app: techchallenge
    spec:
      containers:
        - name: techchallenge
          image: techchallenge:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data-volume-storage
          persistentVolumeClaim:
            claimName: data-volume-claim
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - name: data-volume-storage
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  DATABASE_DIALECT: 'postgres'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'admin'
  POSTGRES_PASSWORD: 'admin'
  POSTGRES_DATABASE: 'app'
  POSTGRES_DB: 'app'
  TYPEORM_CONNECTION: 'postgres'
  TYPEORM_URL: 'postgres://admin:admin@database:5432/app'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: techchallenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge
spec:
  type: NodePort
  selector:
    app: techchallenge
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      name: db-port
