version: '3.7'

# Generate a services using nestjs and postgress stack with dev mode
services:
  app:
    container_name: app
    build:
      context: .docker/
      dockerfile: Dockerfile
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  postgres:
    container_name: database
    image: postgres:latest
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/database_structure.sql:/docker-entrypoint-initdb.d/database_structure.sql
