apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: irsasecrets
      containers:
        - name: sistema-de-lanchonete
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/sistema-de-lanchonete:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 10
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
            - name: DATABASE_DIALECT
              value: 'postgres'
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: dbcredentials 
                  key: host 
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: db
            - name: TYPEORM_CONNECTION
              value: 'postgres'
            - name: TYPEORM_URL
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: typeorm
            - name: PAYMENT_API_URL
              value: 'http://sistema-de-pagamento:3000/payment'
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
      restartPolicy: Always
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: irsasecrets
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::851725345801:role/roleNodeSecrets"