apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: sistema-de-lanchonete
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/sistema-de-lanchonete:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: backend-configmap
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  DATABASE_DIALECT: 'postgres'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'admin'
  POSTGRES_PASSWORD: 'admin'
  POSTGRES_DATABASE: 'app'
  POSTGRES_DB: 'app'
  TYPEORM_CONNECTION: 'postgres'
  TYPEORM_URL: 'postgres://admin:admin@postgresql:5432/app'
  PAYMENT_API_URL: 'http://sistema-de-pagamento:3000/payment'