apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tech_challenge_fiap_4_group_27:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          envFrom:
            - configMapRef:
                name: backend-configmap
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  DATABASE_DIALECT: 'postgres'
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'admin'
  POSTGRES_PASSWORD: 'admin'
  POSTGRES_DATABASE: 'app'
  POSTGRES_DB: 'app'
  TYPEORM_CONNECTION: 'postgres'
  TYPEORM_URL: 'postgres://admin:admin@postgresql:5432/app'
