# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#    name: aws-secrets
# spec:
#   provider: aws
#   parameters:
#     region: us-east-1
#     objects: |
#         - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:dbcredentials-vCmypq"
#           objectAlias: "dbcredentials"
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws   
  secretObjects:
  - secretName: dbcredentials
    type: Opaque
    data:
    - objectName: host
      key: host
    - objectName: port
      key: port
    - objectName: username
      key: username
    - objectName: password
      key: password
    - objectName: db
      key: db
    - objectName: typeorm
      key: typeorm
  parameters:
    region: us-east-1
    objects: | 
        - objectName: "dbcredentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: db
                objectAlias: db
              - path: host
                objectAlias: host
              - path: username
                objectAlias: username
              - path: password
                objectAlias: password
              - path: port
                objectAlias: port
              - path: typeorm
                objectAlias: typeorm